### ISSUE TITLE
AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks

### ISSUE THREAD

**Issue by ligadata-dhaval** [dispatch/dispatch#100]
No method to close HTTP dispatch properly. GIves the below error:

AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks
EBUG [Hashed wheel timer #4] - Entry count for : https://localhost:8081 : 0
TRACE [Hashed wheel timer #4] - 0 channel open, 0 idle channels closed (times: 1st-loop=0, 2nd-loop=0).

TRACE [Hashed wheel timer #2] - 0 channel open, 0 idle channels closed (times: 1st-loop=0, 2nd-loop=0).

DEBUG [Hashed wheel timer #4] - Entry count for : https://localhost:8081 : 0
TRACE [Hashed wheel timer #4] - 0 channel open, 0 idle channels closed (times: 1st-loop=0, 2nd-loop=0).

**Comment by ligadata-dhaval** [comment]
When I use http.shutdown(), it does not show the warning but it still goes on popping DEBUGS:

EBUG [Hashed wheel timer #4] - Entry count for : https://localhost:8081 : 0
TRACE [Hashed wheel timer #4] - 0 channel open, 0 idle channels closed (times: 1st-loop=0, 2nd-loop=0).

TRACE [Hashed wheel timer #2] - 0 channel open, 0 idle channels closed (times: 1st-loop=0, 2nd-loop=0).

DEBUG [Hashed wheel timer #4] - Entry count for : https://localhost:8081 : 0
TRACE [Hashed wheel timer #4] - 0 channel open, 0 idle channels closed (times: 1st-loop=0, 2nd-loop=0).

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
