### ISSUE TITLE
http://databinder.net/dispatch-doc/ reports 403

### ISSUE THREAD

**Issue by davidshen84** [dispatch/dispatch#101]
Would be nice if we have public API doc :)

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
