### ISSUE TITLE
Cannot retrieve request body when parameters are generated from map

### ISSUE THREAD

**Issue by bootkeen** [dispatch/dispatch#102]
version 0.11.2
`"net.databinder.dispatch" %% "dispatch-core" % "0.11.2",`

Tried to get request body when parameters are generated from map:

```
  val u = url("http://example.com") << Map("key" -> "value")
  require(u.toRequest.getStringData != null)

```

It fails although next code works well:

```
  val u = url("http://example.com") << "post body"
  require(u.toRequest.getStringData != null)
```

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
