### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ganeshchand** [dispatch/dispatch#103]
I do not see any activity on this project. What's the future of this project compared to Akka HTTP?

**Comment by SethTisue** [comment]
I think you want https://github.com/dispatch/reboot

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
