### ISSUE TITLE
Scala 2.12

### ISSUE THREAD

**Issue by francisdb** [dispatch/dispatch#104]
dispatch-core_2.12 is not available on maven central, I guess not much needs to be done to do a rebuild of 0.11.3 against scala 2.12.0?

**Comment by francisdb** [comment]
see also https://github.com/dispatch/reboot/issues/134

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
