### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Reldan** [dispatch/dispatch#85]
http://scala-tools.org/repo-releases/net/databinder/

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
