### ISSUE TITLE
0.11.0 - can't post , content length error

### ISSUE THREAD

**Issue by amiracam** [dispatch/dispatch#88]
the docs indicate that something like this should be valid:

val request = url("http://localhost:9292/connect").POST
        request.
            addParameter("user", "charles").
            addParameter("pass", "1234")

```
    val future = (Http(request OK as.String))
    val json = future()
```

unfortunately its refused by the server with a 411 i.e. content length was not set.

Is this a bug or am I missing something in the docs?

thanks

**Comment by alxest** [comment]
I have similar problem [here](https://github.com/dispatch/dispatch/issues/98)

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
