### ISSUE TITLE
Add multipart support for responses

### ISSUE THREAD

**Issue by mirelon** [dispatch/dispatch#95]
When converting response to string using `as.String` and the response is multipart, the resulting string is malformed (contains boundaries and headers from individual parts).

I see there is a support for multipart requests, so I think this is also the place to support multipart responses.

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
