### ISSUE TITLE
Encode URL

### ISSUE THREAD

**Issue by nykolaslima** [dispatch/dispatch#96]
Does dispatch encode the URL that we are passing?

example:
val request = url("http://domain.com.br/some > ugly > url").GET

It's giving me `IllegalArgumentException` but it's a valid URL if you open in a browser for example.
Shouldn't `url` method be smart enough to encode it?

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
