### ISSUE TITLE
Main thread is hanging when launching this simple code via SCALA IDE

### ISSUE THREAD

**Issue by JayChandler** [dispatch/dispatch#97]
Running this simple code in SCALA IDE keeps the application running infinite and hanging why ?

```
  val svc = url("http://www.google.at/");
  val response : Future[String] = Http(svc OK as.String)

  response onComplete {
    case Success(content) => {
      println("Successful response" + content)
    }
    case Failure(t) => {
      println("An error has occurred: " + t.getMessage)
    }
  }
```

Doing this terminates my app successfully

```
Http.shutdown()
```

Why?

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
