### ISSUE TITLE
empty post

### ISSUE THREAD

**Issue by alxest** [dispatch/dispatch#98]
I am using with following sbt config

```
libraryDependencies += "net.databinder.dispatch" %% "dispatch-core" % "0.11.2"
```

And below requests give me 411error (contents length required)

```
Http(url(~~).subject.setMethod("POST") << Map())
Http(url(~~).POST << Map())
Http(url(~~).subject.setMethod("POST"))
Http(url(~~).POST)
```

If I push some dummy value, it works fine.

```
Http(url(~~).subject.setMethod("POST") << Map("" -> ""))
Http(url(~~).POST << Map("" -> ""))
```

I cannot find spec about it in the doc.
Is it intended that above trials fail?
Thank you.

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
