### ISSUE TITLE
Upgrade to latest async-http-client version 1.9.31

### ISSUE THREAD

**Issue by goyalr41** [dispatch/dispatch#99]
The latest async-http-client library version is 1.9.31 but dispatch is using version 1.9.11. This leads to failure while using other libraries because there are changes in both the versions of ning's http-client. Any plans to update the version?

**Comment by samowen-springer** [comment]
+1. 
https://github.com/AsyncHttpClient/async-http-client/issues/201 doesn't appear to be fixed in 1.9.11.

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
